apiVersion: v2
name: goplay-proxy
description: A Helm chart for Go Playground Proxy
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - go
  - golang
  - playground
  - proxy
maintainers:
  - name: Your Name
    email: your-email@example.com
home: https://github.com/yourusername/goplay-proxy
sources:
  - https://github.com/yourusername/goplay-proxy