replicaCount: 1

image:
  repository: ghcr.io/KrypticIO/go-playground-proxy
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

app:
  port: "8080"
  logLevel: "info"

service:
  type: ClusterIP  # Can be ClusterIP, LoadBalancer, or NodePort
  port: 80
  targetPort: http
  # Extra settings for LoadBalancer type
  loadBalancer:
    enabled: false
    annotations: {}
    # loadBalancerIP: "" # Specify if you want a specific IP
    # loadBalancerSourceRanges: [] # Restrict source IPs

ingress:
  enabled: true
  className: "nginx"  # Use the default ingress class or your specific one
  annotations: 
    kubernetes.io/ingress.class: nginx  # Use the same class as your other services
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: goplay-proxy.local
      paths:
        - path: /
          pathType: Prefix  # Changed to Prefix for better compatibility
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5