services:
  go-playground-proxy:
    image: ghcr.io/krypticio/go-playground-proxy:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s